# Site

title: Mini-Languages for Statistical Models
handouts:
  - worksheet.R
 # - worksheet.stan
  - data/README.md
  - data/animals.csv
  - data/plots.csv
  - data/species.csv
#  - data/stanimals.RDS
tag: v0.1
lesson: 2
instructor: Ian Carroll
authors:
  - Ian Carroll

# Slides
slide_sorter:
  - intro
  - formula
  - lm
  - glm
  - lme4
#  - stan
  - conclude
  - solutions

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v1.3/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

github: [metadata]
markdown: kramdown
collections:
  - slides
