# Site

title: Mini-Languages for Statistical Models
handouts:
tag:
lesson: 6
instructor: Ian Carroll
authors:
  - Ian Carroll

# Slides
slide_sorter:
  - intro
  - formula
  - lm
  - glm
  - lme4
  - stan
  - solutions

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/1.1/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
